# will be used as entry in DB to say SITE OFF/ON for healthcheck

server:
    port: 8090
    tomcat:
        max-threads: 50
ssl-enable: false
mso:
  adapters:
    requestDb:
      auth: Basic YnBlbDptc28tZGItMTUwNyE=
      endpoint: http://localhost:8081
  logPath: logs
  site-name: localSite
  infra-requests:
    archived:
      period: 180
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/requestdb
    username: catalog
    password: catalog123
    driver-class-name: org.mariadb.jdbc.Driver
    initialize: true
    initialization-mode: never
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      enable-lazy-load-no-trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    usercredentials:
    -
      username: bpel
      password: '$2a$12$1xyutEZNfjGewIZRfKaE8eZE99f5sYFUmmM80BobI65KNjmcK0JuO'
      role: BPEL-Client
    -  
      username: mso_admin
      password: '$2a$12$tidKuu.h88E2nuL95pTVY.ZOYMN/1dp29A9b1o.0GFDsVVSYlMkHa'
      role: ACTUATOR


flyway:
  baseline-on-migrate: false
  url: jdbc:mariadb://localhost:3306/requestdb
  user: catalog
  password: catalog123
      