# will be used as entry in DB to say SITE OFF/ON for healthcheck
# MSO Properties go here
org:
  onap:
    so:
      adapters:
        default_keystone_url_version: /v2.0
        default_keystone_reg_ex: "/[vV][0-9]"
        vnf:
          bpelauth: 1DDAD7A55A230BB446AA2125053EFB46455F43E48B60155E1C53236E175DFC722A6BE120F6DB390C60034C7564AEB653EA
          checkRequiredParameters: true
          addGetFilesOnVolumeReq: false
          sockettimeout: 30
          connecttimeout: 30
          retrycount: 5
          retryinterval: -15
          retrylist: 408,429,500,502,503,504,900
        network:
          bpelauth: 1DDAD7A55A230BB446AA2125053EFB46455F43E48B60155E1C53236E175DFC722A6BE120F6DB390C60034C7564AEB653EA
          sockettimeout: 5
          connecttimeout: 5
          retrycount: 5
          retryinterval: -15
          retrylist: 408,429,500,502,503,504,900
          encryptionKey: aa3871669d893c7fb8abbcda31b88b4f
        tenant: 
          default_x_aic_orm_client_string: ECOMP-MSO
          default_keystone_url_version: /v2.0
          default_keystone_reg_ex: "/[vV][0-9]"
          default_tenant_description: ECOMP Tenant
          default_region_type: single
          default_user_role: admin
          default_success_status_string: Success
          default_no_regions_status_string: no regions
          default_orm_request_path: /v1/orm/customers/
          default_orm_url_replace_this: 8080
          default_orm_url_replace_with_this: 7080
          default_quota_value: 10
          set_default_quota: false
        po:
          retryCodes: 504
          retryDelay: 5
          retryCount: 3
          pollTimeout: 7500
          pollInterval: 15
      
server-port: 8080
ssl-enable: false
tomcat:
  max-threads: 50
mso:
  logPath: logs
  catalog:
    db:
      spring:
        endpoint: "http://localhost:8080"
  db:
    auth: Basic YnBlbDptc28tZGItMTUwNyE=
  site-name: localDevEnv
  async:
    core-pool-size: 50
    max-pool-size: 50
    queue-capacity: 500
# H2
spring:
  datasource:
    jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    intialize: true
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        enable_lazy_load_no_trans: true
  security:
    usercredentials:
    -  
      username: sdnc
      password: '$2a$12$mukkC6IvLikKGBdwqGnev.H0ccvV6K13TFeLvyNhJoCuNkRjWhqi6'
      role: SDNC-Client
    -  
      username: sitecontrol
      password: '$2a$12$VBUF.qBmeK1FNyO2MqTpD.P2M1tvlesZlhCkAjjHvF9hmYNVdMDmu'
      role: SiteControl-Client 
    -  
      username: bpel
      password: '$2a$12$/GW0/AVAUooTag.7GDc9a.jW7XH3nq/.QsJJJFZJ0N24iXB2W9ksO'
      role: BPEL-Client        
    -  
      username: sniro
      password: '$2a$12$lbOQWS1iDmdQPxW2Mb6OiuTzGaPUrkrvoKVn2zwpFWb6n5Y86Lf1y'
      role: SNIRO-Client  
    -  
      username: apih
      password: '$2a$12$e1BGJ7qknMN/b7bqsQvU2OT9iGunt9IlfQclKlCs6n240oHBfcO5y'
      role: MSO-Client
    -  
      username: mso_admin
      password: '$2a$12$tidKuu.h88E2nuL95pTVY.ZOYMN/1dp29A9b1o.0GFDsVVSYlMkHa'
      role: ACTUATOR

