server:
  port: 9091
  tomcat:
    max-threads: 50
ssl-enable: false
camunda:
  rest:
    api:
      url: http://bpmn-infra:8081/engine-rest/engine/
      engine: default
      auth: Basic YWRtaW46S3A4Yko0U1hzek0wV1hsaGFrM2VIbGNzZTJnQXc4NHZhb0dHbUp2VXkyVQ==
mso:
  database:
    rest:
      api:
        url: http://so-request-db-adapter:8083/infraActiveRequests/
        auth: Basic YnBlbDpwYXNzd29yZDEk
