server:
  port: 9191
  tomcat:
    max-threads: 50
ssl-enable: false
camunda:
  rest:
    api:
      url: http://so-bpmn-infra.onap:8081/sobpmnengine/engine/
      engine: default
      auth: Basic YXBpaEJwbW46cGFzc3dvcmQxJA==
mso:
  database:
    rest:
      api:
        url: http://so-request-db-adapter.onap:8083/infraActiveRequests/
        auth: Basic YnBlbDpwYXNzd29yZDEk
